### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by waveinyu** [waveinyu/vet-clinic#1]
## To-do list
- [ ] Entity 생성
  - [x] animal 동물
  - [ ] guardian 보호자
  - [ ] medical_record 진료 내역
  - [ ] booking_record 예약 내역
  - [ ] payment_record 결제 내역
- [ ] API (Wiki)

해당 프로젝트에 관한 모든 문서는 WIKI에 작성하기
